export default {
  path: 'authorization',
  name: 'authorization-view',
  component: () => import('@/migis/modules/app/authorization/AuthorizationView.vue'),
  redirect: { name: 'authorization-dashboard' },
  children: [
    {
      path: '/',
      name: 'authorization-dashboard',
      component: () => import('@/migis/modules/app/authorization/AuthorizationDashboard.vue'),
      meta: {
        subject: 'ACL-Authorization',
        actions: 'read',
        redirectIfLoggedIn: false,
        tabTitle: 'Ga Inventaris',
        pageTitle: 'AUTHORIZATION',
        layout: '',
        breadcrumb: [
          { text: 'Authorization', active: true },
        ],
        backButton: true,
      },
    },
    {
      path: 'role',
      name: 'authorization-role-dashboard',
      component: () => import('@/migis/modules/app/authorization/RoleDashboard.vue'),
      meta: {
        subject: 'ACL-Authorization',
        actions: 'read',
        redirectIfLoggedIn: false,
        tabTitle: 'Authorization',
        pageTitle: 'AUTHORIZATION ROLE',
        layout: '',
        breadcrumb: [
          { text: 'Authorization', to: {name: 'authorization-dashboard'} },
          { text: 'Role', active: true },
        ],
        backButton: true,
      },
    },
    {
      path: 'role/create',
      name: 'authorization-role-create',
      component: () => import('@/migis/modules/app/authorization/RoleCreate.vue'),
      meta: {
        subject: 'ACL-Authorization',
        actions: 'read',
        redirectIfLoggedIn: false,
        tabTitle: 'Authorization',
        pageTitle: 'AUTHORIZATION ROLE',
        layout: '',
        breadcrumb: [
          { text: 'Authorization', to: {name: 'authorization-dashboard'} },
          { text: 'Role', to: {name: 'authorization-role-dashboard'} },
          { text: 'Buat Baru', active: true },
        ],
        backButton: true,
      },
    },
    {
      path: 'role/:unique/detail',
      name: 'authorization-role-detail',
      component: () => import('@/migis/modules/app/authorization/RoleDetail.vue'),
      meta: {
        subject: 'ACL-Authorization',
        actions: 'read',
        redirectIfLoggedIn: false,
        tabTitle: 'Authorization',
        pageTitle: 'AUTHORIZATION ROLE',
        layout: '',
        breadcrumb: [
          { text: 'Authorization', to: {name: 'authorization-dashboard'} },
          { text: 'Role', to: {name: 'authorization-role-dashboard'} },
          { text: 'Detail', active: true },
        ],
        backButton: true,
      },
    },
    {
      path: 'permission',
      name: 'authorization-permission-dashboard',
      component: () => import('@/migis/modules/app/authorization/PermissionDashboard.vue'),
      meta: {
        subject: 'ACL-Authorization',
        actions: 'read',
        redirectIfLoggedIn: false,
        tabTitle: 'Authorization',
        pageTitle: 'AUTHORIZATION PERMISSION',
        layout: '',
        breadcrumb: [
          { text: 'Authorization', to: {name: 'authorization-dashboard'} },
          { text: 'Permission', active: true },
        ],
        backButton: true,
      },
    },
    {
      path: 'permission/:unique/detail',
      name: 'authorization-permission-detail',
      component: () => import('@/migis/modules/app/authorization/PermissionDetail.vue'),
      meta: {
        subject: 'ACL-Authorization',
        actions: 'read',
        redirectIfLoggedIn: false,
        tabTitle: 'Authorization',
        pageTitle: 'AUTHORIZATION PERMISSION DETAIL',
        layout: '',
        breadcrumb: [
          { text: 'Authorization', to: {name: 'authorization-dashboard'} },
          { text: 'Permission', to: {name: 'authorization-permission-dashboard'} },
          { text: 'Detail', active: true },
        ],
        backButton: true,
      },
    },
  ],
}