export default {
  path: 'okm',
  name: 'okm-view',
  component: () => import('@/migis/modules/app/okm/OKMView.vue'),
  redirect: { name: 'okm-dashboard' },
  children: [
    {
      path: '/',
      name: 'okm-dashboard',
      component: () => import('@/migis/modules/app/okm/OKMDashboardView.vue'),
      meta: {
        subject: 'ACL-OKM',
        actions: 'read',
        redirectIfLoggedIn: false,
        tabTitle: 'OKM',
        pageTitle: 'OKM Dashboard',
        layout: '',
        breadcrumb: [
          { text: 'OKM', active: true },
        ],
        backButton: true,
      },
    },
    {
      path: 'quiz',
      name: 'okm-quiz',
      component: () => import('@/migis/modules/app/okm/OKMDashboardView.vue'),
      meta: {
        subject: 'ACL-OKM',
        actions: 'read',
        redirectIfLoggedIn: false,
        tabTitle: 'OKM',
        pageTitle: 'OKM Dashboard',
        layout: '',
        breadcrumb: [
          { text: 'OKM', active: true },
        ],
        backButton: true,
      },
    },
    {
      path: 'admin',
      name: 'okm-admin-view',
      component: () => import('@/migis/modules/app/okm/admin/AdminView.vue'),
      redirect: { name: 'okm-admin-dashboard' },
      children: [
        {
          path: '/',
          name: 'okm-admin-dashboard',
          component: () => import('@/migis/modules/app/okm/admin/Dashboard.vue'),
          meta: {
            subject: 'ACL-Administrative-OKM',
            actions: 'read',
            redirectIfLoggedIn: false,
            tabTitle: 'OKM Admin',
            pageTitle: 'OKM Administrative Dashboard',
            layout: '',
            breadcrumb: [
              { text: 'OKM', to: {name: 'okm-view'} },
              { text: 'Administrative', active: true },
            ],
            backButton: true,
          },
        },
        {
          path: 'material',
          name: 'okm-admin-material-dashboard',
          component: () => import('@/migis/modules/app/okm/admin/Material.vue'),
          meta: {
            subject: 'ACL-Administrative-OKM',
            actions: 'read',
            redirectIfLoggedIn: false,
            tabTitle: 'OKM Admin',
            pageTitle: 'Database Materi',
            layout: '',
            breadcrumb: [
              { text: 'OKM', to: {name: 'okm-view'} },
              { text: 'Administrative', to: {name: 'okm-admin-view'} },
              { text: 'Material', active: true },
            ],
            backButton: true,
          },
        },
        {
          path: 'question',
          name: 'okm-admin-question-dashboard',
          component: () => import('@/migis/modules/app/okm/admin/Question.vue'),
          meta: {
            subject: 'ACL-Administrative-OKM',
            actions: 'read',
            redirectIfLoggedIn: false,
            tabTitle: 'OKM Admin',
            pageTitle: 'Database Soal',
            layout: '',
            breadcrumb: [
              { text: 'OKM', to: {name: 'okm-view'} },
              { text: 'Administrative', to: {name: 'okm-admin-view'} },
              { text: 'Soal', active: true },
            ],
            backButton: true,
          },
        },
        {
          path: 'question/create',
          name: 'okm-admin-question-create',
          component: () => import('@/migis/modules/app/okm/admin/QuestionCreate.vue'),
          meta: {
            subject: 'ACL-Administrative-OKM',
            actions: 'read',
            redirectIfLoggedIn: false,
            tabTitle: 'OKM Admin',
            pageTitle: 'Tambah Soal',
            layout: '',
            breadcrumb: [
              { text: 'OKM', to: {name: 'okm-view'} },
              { text: 'Administrative', to: {name: 'okm-admin-view'} },
              { text: 'Soal', to: {name: 'okm-admin-question-dashboard'} },
              { text: 'Tambah Soal', active: true },
            ],
            backButton: true,
          },
        },
        {
          path: 'schedule',
          name: 'okm-admin-schedule-dashboard',
          component: () => import('@/migis/modules/app/okm/admin/Schedule.vue'),
          meta: {
            subject: 'ACL-Administrative-OKM',
            actions: 'read',
            redirectIfLoggedIn: false,
            tabTitle: 'OKM Admin',
            pageTitle: 'Jadwal',
            layout: '',
            breadcrumb: [
              { text: 'OKM', to: {name: 'okm-view'} },
              { text: 'Administrative', to: {name: 'okm-admin-view'} },
              { text: 'Schedule', active: true },
            ],
            backButton: true,
          },
        },
      ],
    },
  ],
}